<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>6cb7823b-36f3-42c6-82e5-0eafb9a8765b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/sign_out</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  
                  Logout
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced&quot;]/body[@class=&quot;page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;div ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/header[@class=&quot;page-header ng-scope&quot;]/nav[@class=&quot;navbar mega-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;clearfix navbar-fixed-top&quot;]/div[@class=&quot;topbar-actions&quot;]/div[@class=&quot;btn-group-img btn-group open&quot;]/ul[@class=&quot;dropdown-menu-v2&quot;]/li[3]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
